### ISSUE TITLE
Question: Odd numbered windows are not centered

### ISSUE THREAD

**Issue by EysseW** [DreamMaoMao/hycov#100]
In the showcase video, odd numbered windows are centered. That is not the case on my machine though. How come?
![image](https://github.com/DreamMaoMao/hycov/assets/80292589/6ed1bcd2-7cb6-450d-a457-da9df23e6154)
As you can see, the third window sits in the bottom right instead of being centered in the bottom.

**Comment by DreamMaoMao** [comment]
Could  you record a video  ?

if  it would have the same effect if it were another app?

 It looks like there might be an invisible window occupying this spot.

**Comment by EysseW** [comment]
Ohh good point. I am using xwaylandvideobridge. Maybe a window rule to ignore specified windows could be nice? :D

**Comment by DreamMaoMao** [comment]
there is no this issue when you dont use xwaylandvideobridge?

**Comment by EysseW** [comment]
Indeed, I do not have this issue when xwaylandvideobridge is not running.

**Comment by DreamMaoMao** [comment]
Can you open xwaylandvideobridge and then execute `hyprctl clients` to send the output results to me

**Comment by EysseW** [comment]
I am 99% sure it's due to xwaylandvideobridge, but here you go: `Window 5a857f7591d0 -> WebCord - @Dasvot:
	mapped: 1
	hidden: 0
	at: 16,55
	size: 1048,1849
	workspace: 1 (1)
	floating: 0
	monitor: 2
	class: WebCord
	title: WebCord - @Dasvot
	initialClass: WebCord
	initialTitle: WebCord
	pid: 2031
	xwayland: 1
	pinned: 0
	fullscreen: 0
	fullscreenmode: 0
	fakefullscreen: 0
	grouped: 0
	swallowing: 0
	focusHistoryID: 5

Window 5a857f749bc0 -> foot:
	mapped: 1
	hidden: 1
	at: 1096,255
	size: 936,1009
	workspace: 31 (31)
	floating: 0
	monitor: 0
	class: foot
	title: foot
	initialClass: foot
	initialTitle: foot
	pid: 2271
	xwayland: 0
	pinned: 0
	fullscreen: 0
	fullscreenmode: 0
	fakefullscreen: 0
	grouped: 0
	swallowing: 0
	focusHistoryID: 10

Window 5a85805b9c80 -> Beeper [1] | 0livier:
	mapped: 1
	hidden: 0
	at: 3016,455
	size: 1888,1009
	workspace: 61 (61)
	floating: 0
	monitor: 3
	class: Beeper
	title: Beeper [1] | 0livier
	initialClass: Beeper
	initialTitle: Beeper
	pid: 2661
	xwayland: 1
	pinned: 0
	fullscreen: 0
	fullscreenmode: 0
	fakefullscreen: 0
	grouped: 0
	swallowing: 0
	focusHistoryID: 8

Window 5a85805c5370 -> Steam:
	mapped: 1
	hidden: 0
	at: 1096,255
	size: 1888,1009
	workspace: 31 (31)
	floating: 0
	monitor: 0
	class: steam
	title: Steam
	initialClass: steam
	initialTitle: Steam
	pid: 3255
	xwayland: 1
	pinned: 0
	fullscreen: 0
	fullscreenmode: 0
	fakefullscreen: 0
	grouped: 0
	swallowing: 0
	focusHistoryID: 7

Window 5a85805e89b0 -> Question: Odd numbered windows are not centered · Issue #100 · DreamMaoMao/hycov - Brave:
	mapped: 1
	hidden: 0
	at: 1096,1296
	size: 936,1048
	workspace: 91 (91)
	floating: 0
	monitor: 1
	class: brave-browser-beta
	title: Question: Odd numbered windows are not centered · Issue #100 · DreamMaoMao/hycov - Brave
	initialClass: brave-browser-beta
	initialTitle: [SOLVED] Steam Vulkan games not working after updating Arch / Newbie Corner / Arch Linux Forums - Brave
	pid: 13399
	xwayland: 0
	pinned: 0
	fullscreen: 0
	fullscreenmode: 0
	fakefullscreen: 0
	grouped: 0
	swallowing: 0
	focusHistoryID: 2

Window 5a85806e60e0 -> JamesDSP for Linux:
	mapped: 1
	hidden: 0
	at: 1096,255
	size: 1888,1009
	workspace: 32 (32)
	floating: 0
	monitor: 0
	class: jamesdsp
	title: JamesDSP for Linux
	initialClass: jamesdsp
	initialTitle: JamesDSP for Linux
	pid: 19953
	xwayland: 0
	pinned: 0
	fullscreen: 0
	fullscreenmode: 0
	fakefullscreen: 0
	grouped: 0
	swallowing: 0
	focusHistoryID: 4

Window 5a85806e9f00 -> Your order with order number 310001616239 has been sent - Mozilla Thunderbird:
	mapped: 1
	hidden: 0
	at: 1096,1296
	size: 1888,1048
	workspace: 92 (92)
	floating: 0
	monitor: 1
	class: thunderbird
	title: Your order with order number 310001616239 has been sent - Mozilla Thunderbird
	initialClass: thunderbird
	initialTitle: Mozilla Thunderbird
	pid: 21585
	xwayland: 0
	pinned: 0
	fullscreen: 0
	fullscreenmode: 0
	fakefullscreen: 0
	grouped: 0
	swallowing: 0
	focusHistoryID: 6

Window 5a85807280c0 -> foot:
	mapped: 1
	hidden: 1
	at: 1096,255
	size: 1888,1009
	workspace: 33 (33)
	floating: 0
	monitor: 0
	class: foot
	title: foot
	initialClass: foot
	initialTitle: foot
	pid: 41640
	xwayland: 0
	pinned: 0
	fullscreen: 0
	fullscreenmode: 0
	fakefullscreen: 0
	grouped: 0
	swallowing: 0
	focusHistoryID: 3

Window 5a85807384e0 -> foot:
	mapped: 1
	hidden: 0
	at: 2048,1296
	size: 936,1048
	workspace: 91 (91)
	floating: 0
	monitor: 1
	class: foot
	title: foot
	initialClass: foot
	initialTitle: foot
	pid: 41846
	xwayland: 0
	pinned: 0
	fullscreen: 0
	fullscreenmode: 0
	fakefullscreen: 0
	grouped: 0
	swallowing: 0
	focusHistoryID: 0

Window 5a85805d2d60 -> Special Offers:
	mapped: 1
	hidden: 0
	at: 1687,-629
	size: 706,830
	workspace: 31 (31)
	floating: 1
	monitor: 0
	class: steam
	title: Special Offers
	initialClass: steam
	initialTitle: Special Offers
	pid: 3255
	xwayland: 1
	pinned: 0
	fullscreen: 0
	fullscreenmode: 0
	fakefullscreen: 0
	grouped: 0
	swallowing: 5a857f749bc0
	focusHistoryID: 9

Window 5a858072d5c0 -> Wayland to X Recording bridge — Xwayland Video Bridge:
	mapped: 1
	hidden: 0
	at: 2061,400
	size: 1,1
	workspace: 33 (33)
	floating: 1
	monitor: 0
	class: xwaylandvideobridge
	title: Wayland to X Recording bridge — Xwayland Video Bridge
	initialClass: xwaylandvideobridge
	initialTitle: Wayland to X Recording bridge — Xwayland Video Bridge
	pid: 41811
	xwayland: 1
	pinned: 0
	fullscreen: 0
	fullscreenmode: 0
	fakefullscreen: 0
	grouped: 0
	swallowing: 5a85807280c0
	focusHistoryID: 1


`

**Comment by DreamMaoMao** [comment]
![image](https://github.com/DreamMaoMao/hycov/assets/30348075/d571a2ca-933f-42e0-b199-1c6a4919b1e2)

It seems that there is a window that is not resizable but is very small that occupies this position

**Comment by DreamMaoMao** [comment]
There is no good way to deal with it at the moment, because this is the problem of the software window itself, not the problem of hycov
