### ISSUE TITLE
Please update this plugin

### ISSUE THREAD

**Issue by mahaveergurjar** [DreamMaoMao/hycov#101]
After update hyprland this pkugin not work so please update this plugin

❯ hyprctl systeminfo
Hyprland, built from branch  at commit cba1ade848feac44b2eda677503900639581c3f4  (props: bump version to 0.40.0).
Date: Sat May 4 15:42:32 2024
Tag: v0.40.0, commits: 4606

flags: (if any)

System Information:
System name: Linux
Node name: archlinux
Release: 6.8.9-arch1-2
Version: #1 SMP PREEMPT_DYNAMIC Tue, 07 May 2024 21:35:54 +0000

GPU information: 
0000:00:02.0 VGA compatible controller [0300]: Intel Corporation Alder Lake-UP3 GT2 [UHD Graphics] [8086:4628] (rev 0c) (prog-if 00 [VGA controller])

os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo

plugins:

![image](https://github.com/DreamMaoMao/hycov/assets/57872034/a08f3531-464c-4bb4-840d-f6ce948c828a)
![image](https://github.com/DreamMaoMao/hycov/assets/57872034/e55eaa81-6d5f-46b2-8b72-b10863767482)

**Comment by DreamMaoMao** [comment]
![image](https://github.com/DreamMaoMao/hycov/assets/30348075/fd2f3e33-5ccf-4dcb-b729-edf13b3e063f)

There may be a problem with the way you update, this plugin already supports 0.40 release

**Comment by mahaveergurjar** [comment]
ok i reinstall the hycov
