### ISSUE TITLE
Bring floating window to top, after switching focus

### ISSUE THREAD

**Issue by saipavanc** [DreamMaoMao/hycov#104]
The way I have it setup, I am using alt+tab to switch to the next window on release of alt. But if windows are floating, it would be necessary to get the focussed window to top using alterzorder. Maybe adding such an option would be nice, if someone does not want that to happen.

**Comment by DreamMaoMao** [comment]
I will consider adding this option in the next version

**Comment by DreamMaoMao** [comment]
![Uploading image.png…]()
 
done

**Comment by DreamMaoMao** [comment]
![image](https://github.com/DreamMaoMao/hycov/assets/30348075/219a0025-5788-410f-ab10-195729e3fd91)

done
