### ISSUE TITLE
[FR] toggle overview - only active workspace dispatcher

### ISSUE THREAD

**Issue by luravoid** [DreamMaoMao/hycov#105]
I know I can set only_active_workspace = 1 and use hycov:toggleoverview,forceall if I want to see the overview of all windows.

However, entering the overview using hot corners will also show only the active workspace, whereas I want this behavior only with a specific binding.

So, it would be nice to have something like hycov:toggleoverview,onlyactiveworkspace.

**Comment by DreamMaoMao** [comment]
![image](https://github.com/DreamMaoMao/hycov/assets/30348075/fb0d292d-5606-4fab-9926-9f2bc218e30a)
