### ISSUE TITLE
hy3 compatability

### ISSUE THREAD

**Issue by KCkingcollin** [DreamMaoMao/hycov#106]
any chance for hy3 compatibility?
seems to work great on its own, but it doesn't detect tabbed windows. this plugin would be perfect for my setup otherwise. wish i could try to implement it myself, but im far from being able to understand c or c++ enough to fix this myself

**Comment by DreamMaoMao** [comment]
what is that mean that it doesn't detect tabbed windows?

**Comment by DreamMaoMao** [comment]
https://github.com/DreamMaoMao/hycov/assets/30348075/e303246e-4262-429c-afb4-cdfd8b4b1ea4

I have no problem when using hy3

**Comment by DreamMaoMao** [comment]
![image](https://github.com/DreamMaoMao/hycov/assets/30348075/c13e112f-0076-4699-b12c-413196218387)


BTW I was testing with the latest hy3 release, not hy3-git

**Comment by KCkingcollin** [comment]
> what is that mean that it doesn't detect tabbed windows?

As in, when you group windows into tabs the windows that aren't focused are not shown in the preview, and the tabs themselves are left visible, I could make a video later today, but rn I'm off the PC for the rest of the night while I get some sleep

**Comment by KCkingcollin** [comment]
> ![image](https://private-user-images.githubusercontent.com/30348075/338039892-c13e112f-0076-4699-b12c-413196218387.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwMDA4NTEsIm5iZiI6MTcxODAwMDU1MSwicGF0aCI6Ii8zMDM0ODA3NS8zMzgwMzk4OTItYzEzZTExMmYtMDA3Ni00Njk5LWIxMmMtNDEzMTk2MjE4Mzg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEwVDA2MjIzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2MzE2NTQ5ZWIwY2Y4Y2VlNDI4NTBmNTdmMTc1NjIyYzk4NjQxNmJjNGY5ODRjMzg0MTYzMjRlZmRlMzljNzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.J0zkT35E2yg6E39KUtL5SbZa2AVFn_fBWug0qcMtRos)
> 
> BTW I was testing with the latest hy3 release, not hy3-git

I'm using the stable hyprland build in the extra repos, and using hyprpm to manage my plugins

**Comment by DreamMaoMao** [comment]
> > what is that mean that it doesn't detect tabbed windows?
> 
> As in, when you group windows into tabs the windows that aren't focused are not shown in the preview, and the tabs themselves are left visible, I could make a video later today, but rn I'm off the PC for the rest of the night while I get some sleep

Still don't understand what's going on, what is tag?

**Comment by KCkingcollin** [comment]
> > > what is that mean that it doesn't detect tabbed windows?
> > 
> > As in, when you group windows into tabs the windows that aren't focused are not shown in the preview, and the tabs themselves are left visible, I could make a video later today, but rn I'm off the PC for the rest of the night while I get some sleep
> 
> Still don't understand what's going on, what is tab?
> 

You can create grups of windows with the ``hy3:changegroup, toggletab`` dispatcher in hy3. When making groups it creates tabs for each window in the group, im currently working rn otherwise I'd show you, but you can try it in your hyprland config if you use hy3, I personally bind it to Super+G

**Comment by DreamMaoMao** [comment]
emm.. This looks like hy3 implementing a group on its own, But I have no plans to read hy3 code.

so sorry about my helpless.

**Comment by KCkingcollin** [comment]
> emm.. This looks like hy3 implementing a group on its own, But I have no plans to read hy3 code.
> 
> so sorry about my helpless.
> 

That's ok, I understand. Thanks anyway. Maybe one day I'll learn c and fork this project myself, but in the meantime, this is still a great plugin
