### ISSUE TITLE
Is enable_hotarea bundled with enable_click_action

### ISSUE THREAD

**Issue by hengtseChou** [DreamMaoMao/hycov#108]
Hi, I recently installed hycov and I enjoyed your work very much. However, when I try to set `enable_click_action` as 0 and `enable_click_action` as 1 to disable hot area and keep click actions to jump/kill windows, it did not work. It seems like click action is only usable when hotarea is enabled? Is there a way to disable hotarea while keeping the click action working? Thank you very much.

**Comment by DreamMaoMao** [comment]
it work for me ,  what hyprland version you use

**Comment by DreamMaoMao** [comment]
![image](https://github.com/DreamMaoMao/hycov/assets/30348075/6745a65e-c9f2-4499-aa1c-4df8978e6dc5)

what is that mean.

**Comment by DreamMaoMao** [comment]
you should set enable_hotarea to 0, and set enable_click_action to 1

**Comment by hengtseChou** [comment]
I am using hyprland 0.39 since 0.40 is buggy for me.

I do set the config like this

```
plugin {
    hycov {
        enable_hotarea = 0
        enable_click_action = 1
    }
}
```

but it didn't work

**Comment by DreamMaoMao** [comment]
0.39 not support enable_click_action

you can just set 

enable_hotarea = 1
hotarea_size = 0


it also can't disable hot corner and enable click action

**Comment by hengtseChou** [comment]
it worked! many thanks
