### ISSUE TITLE
Window order based on chronological usage

### ISSUE THREAD

**Issue by LewentalDigital** [DreamMaoMao/hycov#109]
Would be great if the windows in overview could be ordered chronologically, so that the closest one in the cycle is the latest window i used.

This could improve workflow so that it is faster to switch focus between frequently used programs.

**Comment by DreamMaoMao** [comment]
Isn't it chronological now?  
The way it's sorted now is by the time it started

**Comment by LewentalDigital** [comment]
Sorry, maybe I wasn't clear

Now it's chronological based on the time when the window is first opened;
What I am suggesting is based on the time of latest usage of the window: 
when i move focus to a window, that window is the latest used window, so it should go to the top in the order;
the least used window should be the last in the order.
This ordering should be dynamic, updated every time the focus changes.

So when toggling the overview I cycle trough the most recent windows i used.
Like the behaviour of alt tab in kde or windows.

Let me know if I should be more clear

**Comment by DreamMaoMao** [comment]
sorry no this plan
