### ISSUE TITLE
Workspace issue

### ISSUE THREAD

**Issue by killown** [DreamMaoMao/hycov#12]
any way to get only windows from current workspace, actually, it's getting all windows from all workspaces, if I click in a window which is not into the current workspace, it moves for an empty workspace and all windows disappear.

Even so, I would like the behavior of only showing windows from current workspace, can you implement that?

**Comment by DreamMaoMao** [comment]
I don't quite understand your requirements, in fact, this plugin is just a plugin for switching workspaces, how to use it in a workspace? Or do you just want a grid layout?

**Comment by killown** [comment]
> I don't quite understand your requirements, in fact, this plugin is just a plugin for switching workspaces, how to use it in a workspace? Or do you just want a grid layout?

for example, there is two windows in workspace 1 and 1 window in workspace 7, if I toggle the overview, all 3 windows will be displayed, I would like the overview only showing the two windows from workspace 1 which is the active workspace

**Comment by killown** [comment]
https://github.com/DreamMaoMao/hycov/assets/24453/9c235c36-905c-4d71-876e-60ec2ada3e78

workspace 1: two gnome-terminal
workspace 7: hbo max window
the overview is showing all windows, but when I click in the hbo max window while in workspace 1, all windows disappear

**Comment by DreamMaoMao** [comment]
This is a strange requirement, because in wm, the Windows of a workspace are already tiled (they don't block each other).

**Comment by DreamMaoMao** [comment]
> output.mp4 
> workspace 1: two gnome-terminal workspace 7: hbo max window the overview is showing all windows, but when I click in the hbo max window while in workspace 1, all windows disappear

your video is broken , i can't see anything

**Comment by killown** [comment]
> > output.mp4
> > workspace 1: two gnome-terminal workspace 7: hbo max window the overview is showing all windows, but when I click in the hbo max window while in workspace 1, all windows disappear
> 
> your video is broken , i can't see anything

can you download the video and play it locally?

**Comment by killown** [comment]
https://github.com/DreamMaoMao/hycov/assets/24453/0e93971f-54cf-4a7b-8d1a-21f5bf857dd6

**Comment by DreamMaoMao** [comment]
Did you used the latest hycov source code ?

**Comment by DreamMaoMao** [comment]
what is your hyrpland version , `hyprctl version ` to show me

**Comment by killown** [comment]
could you instead of changing to active source workspace, change to workspace from focused window    ?
that would fix the issue

**Comment by DreamMaoMao** [comment]
the same operation here is no problem for me, other people are no problem, this problem just appears in you.

**Comment by DreamMaoMao** [comment]
https://github.com/DreamMaoMao/hycov/assets/30348075/1692f2a1-d75e-4466-9c7f-3d131e59adce

**Comment by killown** [comment]
Do you use multi monitor setup? I am using two monitors

**Comment by DreamMaoMao** [comment]
yes i had test it on molti monitor. I haven't updated the hyprland version in a long time and I need some time to test the new version

**Comment by killown** [comment]
> yes i had test it on multi monitor. I haven't updated the hyprland version in a long time and I need some time to test the new version

oh, so this is it, hyprland changed something that broke your plugin

**Comment by DreamMaoMao** [comment]
I have tested it and it does not work under the latest hyprland source code..

**Comment by killown** [comment]
fixed by commenting 

```
    //change all client workspace to active worksapce 
     //if (pWindowOriWorkspace->m_iID != pActiveWorkspace->m_iID || pWindowOriWorkspace->m_szName != pActiveWorkspace->m_szName)
    //{
     //   pNode->workspaceID = pWindow->m_iWorkspaceID = pActiveWorkspace->m_iID;
    //    pNode->workspaceName = pActiveWorkspace->m_szName;
    //}
```

So now it has the behavior I want for, only show windows from active workspace, also, g_pCompositor->setWindowFullscreen(n.pWindow, true, FULLSCREEN_MAXIMIZED );    maximize the focused window


thank you

**Comment by DreamMaoMao** [comment]
![image](https://github.com/DreamMaoMao/hycov/assets/30348075/6e100130-9571-4cb7-bb3c-4c3652ee398c)


THe functional options have been added
