### ISSUE TITLE
Window switching from desktop 1 to desktop 2

### ISSUE THREAD

**Issue by craftergarage** [DreamMaoMao/hycov#13]
When I use hycov on open windows while on desktop1, when I click on one of the windows on desktop1, it goes to that window, but when I go to hycov while on desktop1 and want to go to one of the windows on desktop2, it goes to a blank screen. What could be the reason for this error?

https://github.com/DreamMaoMao/hycov/assets/121237802/4df461c2-d909-410c-9da6-319af20662bd

**Comment by DreamMaoMao** [comment]
It seems that hyprland updated some of the interfaces, causing problems with the plug-in's original interface calls.

**Comment by DreamMaoMao** [comment]
Maybe you can roll back the hyprland version to v0.30.1,I don't have time to follow up on hyprland updates right now

**Comment by DreamMaoMao** [comment]
log.sh
```
#!/usr/bin/bash
a=$(cd /tmp/hypr/ && ls -rt | tail -1)
tail -f /tmp/hypr/$a/hyprland.log
```

bash log.sh >> log.txt

You can run this script and repeat your problem above, then send me log.txt

**Comment by craftergarage** [comment]
sure There is no error log

[log.txt](https://github.com/DreamMaoMao/hycov/files/13499618/log.txt)

**Comment by DreamMaoMao** [comment]
![image](https://github.com/DreamMaoMao/hycov/assets/30348075/26af84f2-aec8-4da4-87db-ec3c6bb15e27)
I'm not looking for an error log. I'm looking for a behavior log

The content in your log is not what I want, please update hycov. I just updated some things, then run this script, and then continue to do what you did before(like video), and then send the log to me

**Comment by DreamMaoMao** [comment]
![image](https://github.com/DreamMaoMao/hycov/assets/30348075/94a850c4-6fa6-4544-9825-466bb02168e6)

**Comment by craftergarage** [comment]
[log.txt](https://github.com/DreamMaoMao/hycov/files/13499961/log.txt)


First of all, thank you for taking care of me on this matter. :)


When I perform the same operations again, this is all that is added to the log section.

**Comment by craftergarage** [comment]
Your interface is very nice, I liked it. Have you shared dotfiles before?

**Comment by DreamMaoMao** [comment]
There still doesn't seem to be a real-time log of any relevant behavior, So I can't make any judgment.

`/tmp/hypr/` Maybe you need to look in this directory for your latest live logs

**Comment by DreamMaoMao** [comment]
https://github.com/DreamMaoMao/hycov/assets/30348075/cfeeef30-cc3f-4da8-896b-1cb8254fcbb1

it will show the live message

**Comment by craftergarage** [comment]
I found the reason for not writing log records. Because the default "disable_logs" parameter in hyprland debug is true. I fixed this and now I can get the logs. I printed the logs in txt file.


[log.txt](https://github.com/DreamMaoMao/hycov/files/13500427/log.txt)

**Comment by craftergarage** [comment]
"[LOG] OPENING ON: [Node nullptr], Monitor: 0"

 I saw this part in the logs. Could the error be caused by this part because it is null?

**Comment by DreamMaoMao** [comment]
Are you using multi monitor?

**Comment by craftergarage** [comment]
Yes, I use multi at home, but in the office there is only a laptop screen. Currently, however, I have not changed the Hyprland default settings yet.

**Comment by DreamMaoMao** [comment]
can you show me you config of hyprland.conf?  

I seem to remember that someone also tried to feedback this error to me before, as if it was because of the monitor configuration in hyprland.conf

**Comment by craftergarage** [comment]
########################################################################################
AUTOGENERATED HYPR CONFIG.
PLEASE USE THE CONFIG PROVIDED IN THE GIT REPO /examples/hypr.conf AND EDIT IT,
OR EDIT THIS ONE ACCORDING TO THE WIKI INSTRUCTIONS.
########################################################################################

#
# Please note not all available settings / options are set here.
# For a full list, see the wiki
#

# autogenerated = 1 # remove this line to remove the warning

# See https://wiki.hyprland.org/Configuring/Monitors/
monitor=,preferred,auto,auto


# See https://wiki.hyprland.org/Configuring/Keywords/ for more

# Execute your favorite apps at launch
# exec-once = waybar & hyprpaper & firefox

# Source a file (multi-file configs)
# source = ~/.config/hypr/myColors.conf

# Some default env vars.
env = XCURSOR_SIZE,24

# For all categories, see https://wiki.hyprland.org/Configuring/Variables/
input {
    kb_layout = tr
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1

    touchpad {
        natural_scroll = no
    }

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
}

general {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    gaps_in = 5
    gaps_out = 20
    border_size = 2
    col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    col.inactive_border = rgba(595959aa)

    layout = dwindle
}

decoration {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    rounding = 10
    
    blur {
        enabled = true
        size = 3
        passes = 1
    }

    drop_shadow = yes
    shadow_range = 4
    shadow_render_power = 3
    col.shadow = rgba(1a1a1aee)
}

animations {
    enabled = yes

    # Some default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more

    bezier = myBezier, 0.05, 0.9, 0.1, 1.05

    animation = windows, 1, 7, myBezier
    animation = windowsOut, 1, 7, default, popin 80%
    animation = border, 1, 10, default
    animation = borderangle, 1, 8, default
    animation = fade, 1, 7, default
    animation = workspaces, 1, 6, default
}

dwindle {
    # See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
    pseudotile = yes # master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = yes # you probably want this
}

master {
    # See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
    new_is_master = true
}

gestures {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more
    workspace_swipe = off
}

# Example per-device config
# See https://wiki.hyprland.org/Configuring/Keywords/#executing for more
device:epic-mouse-v1 {
    sensitivity = -0.5
}

# Example windowrule v1
# windowrule = float, ^(kitty)$
# Example windowrule v2
# windowrulev2 = float,class:^(kitty)$,title:^(kitty)$
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more


# See https://wiki.hyprland.org/Configuring/Keywords/ for more
$mainMod = SUPER

# Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
bind = $mainMod, Q, exec, foot
bind = $mainMod, C, killactive, 
bind = $mainMod, M, exit, 
bind = $mainMod, E, exec, dolphin
bind = $mainMod, V, togglefloating, 
bind = $mainMod, R, exec, wofi --show drun
#bind = $mainMod, P, pseudo, # dwindle
bind = $mainMod, J, togglesplit, # dwindle

# Move focus with mainMod + arrow keys
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d

# Switch workspaces with mainMod + [0-9]
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10

# Scroll through existing workspaces with mainMod + scroll
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow


debug {
	disable_logs = false
	enable_stdout_logs = true
}


# when enter overview, you can use letf-button to jump,right-button to kill or use keybind
plugin = /usr/lib/libhycov.so
bind = CTRL_ALT,h,hycov:enteroverview
bind = CTRL_ALT,m,hycov:leaveoverview
bind = CTRL_ALT,k,hycov:toggleoverview

# The direction switch shortcut key binding.
# calculate the window closest to the direction to switch focus.
# This keybind is applicable not only to the overview  but also to the general layout
bind=ALT,left,hycov:movefocus,l
bind=ALT,right,hycov:movefocus,r
bind=ALT,up,hycov:movefocus,u
bind=ALT,down,hycov:movefocus,d

plugin {
    hycov {
        overview_gappo = 60 # gas width from screem 
        overview_gappi = 24 # gas width from clients
	      hotarea_size = 10 # hotarea size in bottom left,10x10
	      enable_hotarea = 1 # enable mouse cursor hotarea     
        swipe_fingers = 4 # finger number of gesture,move any directory
        move_focus_distance = 100 # distance for movefocus,only can use 3 finger to move 
        enable_gesture = 0 # enable gesture
        disable_workspace_change = 0 # disable workspace change when in overview mode
        disable_spawn = 0 # disable bind exec when in overview mode
        auto_exit = 1 # enable auto exit when no client in overview
    }
}

**Comment by craftergarage** [comment]
My setup is like this by default. There is not much customization at the moment. First of all, I wanted to solve this problem. I just formatted my computer today.

monitor=,preferred,auto,auto

**Comment by DreamMaoMao** [comment]
The log shows that your error is most likely caused by the monitor configuration
You can use the hyprctl monitor to obtain the specific monitor id for specific Settings
![image](https://github.com/DreamMaoMao/hycov/assets/30348075/987c121f-fae7-4717-b58d-fd94692f437b)
![image](https://github.com/DreamMaoMao/hycov/assets/30348075/1f371752-6997-453e-8b6c-3678a689456c)

**Comment by craftergarage** [comment]
I made the settings you said. The error continues the same way.

https://github.com/DreamMaoMao/hycov/assets/121237802/aba59aaf-70ea-49b5-af49-c2ecc8490835

last log file
[log.txt](https://github.com/DreamMaoMao/hycov/files/13501561/log.txt)


Can you give me the Hyprland configurations you use so that I can compare them, if it is a configuration-related error?

**Comment by DreamMaoMao** [comment]
![image](https://github.com/DreamMaoMao/hycov/assets/30348075/db49af5f-404e-4ecb-b912-a9e816afd405)
![image](https://github.com/DreamMaoMao/hycov/assets/30348075/918c8d7e-ebd3-49e3-8b17-8312bb29a835)

I don't have this error here, my configuration is the one you see above
![image](https://github.com/DreamMaoMao/hycov/assets/30348075/0a1e896e-b00d-4566-a96c-6c08bd974333)

**Comment by DreamMaoMao** [comment]
Well, I know the problem,hyprland updated some things, causing some rendering logic can not be adapted, I removed some things to adapt the new hyprland, although the animation effect is not as good as the previous one, but it can be used

and you can try the latest hycov code.

**Comment by craftergarage** [comment]
thank you very much. yes it worked now :D you are great.
