### ISSUE TITLE
FEATURE: Dispatcher Overview only active workspaces; Dispatcher Overiew workspaces

### ISSUE THREAD

**Issue by fedoranvar** [DreamMaoMao/hycov#14]
Good day to you!

I've suggestion for features:

* Dispatcher for overviewing clients only of active workspaces: 
`hycov:toggleactiveoverview`

* Dispatcher overview workspaces:
`hycov:toggleworkspaceoverview`

* Option for overiew without clients in hidden special workspaces

Thank you!

**Comment by DreamMaoMao** [comment]
Functional options have been added
![image](https://github.com/DreamMaoMao/hycov/assets/30348075/9bd83a19-ad92-477e-870c-49b48608d988)

The special workspace window has been disabled from overview


on the side, The  workspace overview is not the target of this plug-in; the target of this plug-in is client overview
