### ISSUE TITLE
BUG: hidden special workspaces not focusing; bugged positiononing

### ISSUE THREAD

**Issue by fedoranvar** [DreamMaoMao/hycov#15]
Good day to you!

My system config for current date: 
* latest hyprland commit
* latest hycov commit
* configure by NixOS home-manager module
* multi-monitor setup

noticed some bugs:

* clients from hidden special workspaces not focusing from overview, from visible special workspace - focusing

* Bugged positioning or clients 'flying away' in overview:
![image](https://github.com/DreamMaoMao/hycov/assets/52028706/b8fde5b6-fcc6-462f-94f6-9c0bdca21092)

'flying away' when only one client on monitor:

https://github.com/DreamMaoMao/hycov/assets/52028706/dbd96664-13f4-4deb-b173-a8c100ecaf8c

Thank you!

**Comment by DreamMaoMao** [comment]
All your descriptions,

I'm not sure what you're talking about, but special workspaces should be excluded, I've already excluded special workspaces, you can try the latest code

**Comment by DreamMaoMao** [comment]
The Angle of your video is so weird, I can't see anything

**Comment by DreamMaoMao** [comment]
If these are clients on a particular workspace you can try the latest code first

**Comment by DreamMaoMao** [comment]
may fixed: #49
