### ISSUE TITLE
active window disappeared

### ISSUE THREAD

**Issue by craftergarage** [DreamMaoMao/hycov#16]
Hello Dream;

With the 7348f4c update, hycov was working fine.

With the c134aed update, I encounter an error like the one in the video in hycov.

"dekstop" I have 1,2,3,4 windows

There are 3 terminals open on Dekstop 1. I listed the screens with hycov and when I selected one of the 3 terminals, the other two terminal screens disappeared. It continues to run in the background. It appears again when I change the window mode. why did this happen? can you fix this for me?

https://github.com/DreamMaoMao/hycov/assets/121237802/2273b232-3501-4807-b392-1adc8293af30

[log.txt](https://github.com/DreamMaoMao/hycov/files/13539537/log.txt)

[log2.txt](https://github.com/DreamMaoMao/hycov/files/13539538/log2.txt)

I am also attaching the log file.

**Comment by DreamMaoMao** [comment]
This feature was previously turned on by default and I have set it to be disabled by default to avoid confusion

**Comment by DreamMaoMao** [comment]
You're welcome. In addition, Could you possibly tell me how you made your window border have many colors, which looks pretty cool.

**Comment by DreamMaoMao** [comment]
You're welcome. In addition, Could you possibly tell me how you made your window border have many colors, which looks pretty cool.
@craftergarage
