### ISSUE TITLE
Add option for infinite scrolling

### ISSUE THREAD

**Issue by IceDBorn** [DreamMaoMao/hycov#22]
It would be nice having an option of infinite scrolling. That way you could bind `ALT + TAB` for example to `hycov:toggleoverview` and `hycov:movefocus,l` and have an alt tab experience closer to common alt tab implementations for quickly switching between two or more windows.

**Comment by DreamMaoMao** [comment]
yd 不是很明白你要的效果,你是说将一个快捷键同时绑定到触发和
切换焦点?

**Comment by DreamMaoMao** [comment]
Not quite sure what you're looking for, you're talking about binding a shortcut to both trigger and toggle focus? Are there any relevant cases for my reference?

**Comment by DreamMaoMao** [comment]
done , you can see the latest readme

**Comment by DreamMaoMao** [comment]
![image](https://github.com/DreamMaoMao/hycov/assets/30348075/1864a045-1b6f-4d9f-92e2-444d026990e7)
