### ISSUE TITLE
Closing focused window on overview mode jumps to another workspace

### ISSUE THREAD

**Issue by IceDBorn** [DreamMaoMao/hycov#24]
When in overview mode, closing the focused window, makes hyprland switch to another workspace. The workspace, I toggled the overview mode on, had 2 windows and I have 2 monitors attached.

**Comment by DreamMaoMao** [comment]
I don't see what you mean,Can you give me more information?

**Comment by IceDBorn** [comment]
What kind of information do you need? Both nixpkgs and hyprland at the latest hash too.

**Comment by DreamMaoMao** [comment]
have fixed , you can try all fo you issue in latest main branch

**Comment by IceDBorn** [comment]
I just tried it and it works, thanks a lot for this great project!
