### ISSUE TITLE
Add option for auto-selecting next window on overview toggle

### ISSUE THREAD

**Issue by IceDBorn** [DreamMaoMao/hycov#27]
You implemented the traditional alt tab functionality, and I thank you for that. Now, I would love if we had the option to auto-select the next window when the alt release mechanism is enabled.

**Comment by DreamMaoMao** [comment]
I don't think this is a good idea, because the plugin is also compatible with users who use directional switching, and for users who use directional switching, they can't determine what the next window is after triggering overview

**Comment by IceDBorn** [comment]
Well, that's why it can be an option which you'll be able to set to 0 or 1.

**Comment by DreamMaoMao** [comment]
done 
![image](https://github.com/DreamMaoMao/hycov/assets/30348075/10d1472d-ad20-431e-81b6-843127544c18)
