### ISSUE TITLE
New dispatcher for all windows

### ISSUE THREAD

**Issue by IceDBorn** [DreamMaoMao/hycov#28]
I use the option `only_active_workspace` but sometimes I would like to overview windows from all workspaces, even all monitors. So, I'm asking for another dispatcher that toggles the overview mode in a state that shows windows from all workspaces, regardless of the value of the option.

**Comment by DreamMaoMao** [comment]
done
![image](https://github.com/DreamMaoMao/hycov/assets/30348075/0cfff080-13a3-4777-9d04-dfb5b1f1e14b)
