### ISSUE TITLE
Only 2 windows visible for secondary monitors

### ISSUE THREAD

**Issue by DashieTM** [DreamMaoMao/hycov#3]
When using the overview effect, only 2 windows can be used on secondary screens.
If there are more, no matter if they are in a different workspace, the windows will vanish when in overview mode and come back after.
The main monitor is not affected and can use as many windows as one wants.

https://github.com/DreamMaoMao/hycov/assets/72016555/f7fed184-5b44-41c5-bf10-d12b0a988a5d

Despite the small bug, awesome work!

**Comment by DreamMaoMao** [comment]
Can you show me the configuration of the `monitor setting` in `hyprland.conf`

**Comment by DashieTM** [comment]
of course:
```
monitor=DP-3,2560x1440@165,-2560x0,1
monitor=DP-1,3440x1440@180,0x0,1
monitor=DP-2,1920x1200@60,3440x0,1
monitor=DP-2,transform,1
```
I also tried it without a negative offset:
```
monitor=DP-3,2560x1440@165,0x0,1
monitor=DP-1,3440x1440@180,2560x0,1
monitor=DP-2,1920x1200@60,6000x0,1
monitor=DP-2,transform,1
```

**Comment by DreamMaoMao** [comment]
Can you try the latest dev branch?

https://github.com/DreamMaoMao/hycov/tree/dev

git clone -b dev https://github.com/DreamMaoMao/hycov.git

**Comment by DreamMaoMao** [comment]
could you try whether this branch fixes the negative offset of the monitor. The hdmi interface of my computer is broken, and i cannot  test it for the time being

**Comment by DashieTM** [comment]
The same behavior sadly for both configurations.
I have also recorded what happens without a negative offset.
It seems that after more than 2 windows, the windows want to move to a different location.

https://github.com/DreamMaoMao/hycov/assets/72016555/2213b2de-8b6b-4b16-ae28-fd18700efff1

**Comment by DashieTM** [comment]
I added the offsets for the monitors for each case, the pr shouldn't do anything drastic but a quick check is always good.

https://github.com/DreamMaoMao/hycov/assets/72016555/066f3f71-8ccd-4235-887b-0cdb9a3ca4c4

**Comment by DreamMaoMao** [comment]
has fixed , you can try lastest commit in main branch

**Comment by DashieTM** [comment]
Both solutions work, feel free to choose which one you would like.
