### ISSUE TITLE
Alt + arrow keys works even when hycov is not toggled

### ISSUE THREAD

**Issue by Deeepkk** [DreamMaoMao/hycov#30]
when pressed alt + left/right keys normally , it switches the window. They should just work when hycov is toggled by alt+tab. It is conflicting with browser since usually browser also assign alt + left as previous page key.

**Comment by DreamMaoMao** [comment]
![image](https://github.com/DreamMaoMao/hycov/assets/30348075/9d4fa2bd-2288-4cda-9b83-53e2e30a15f4)
it is not a bug, you can bind the direction switch to other key

**Comment by Deeepkk** [comment]
I also had this thought but it would be nice if those key only worked when hycov is toggled, it is kinda useless for other scenario. 
Btw thankyou for making this project.

**Comment by DreamMaoMao** [comment]
why it is useless,How do you switch window focus in normal mode? I also use it to switch window focus when in normal mode.
