### ISSUE TITLE
Remembering tiled windows placement.

### ISSUE THREAD

**Issue by kragebein** [DreamMaoMao/hycov#32]
I have certain workspaces where i have a specific setup of tiled clients. 
But when i use hycov, it places the windows back into that workspace, at random, and not in the same way they were tiled before.

Before:
![image](https://github.com/DreamMaoMao/hycov/assets/19599766/6f6f341e-f6e8-4236-85ba-b5a4a86500cf)

After:
![image](https://github.com/DreamMaoMao/hycov/assets/19599766/6c86c5d8-3091-41cc-bc21-a4f68eeebee7)

I'd like to request a feature enhancement where hycov ensures that the placement of the clients are rememberd.

**Comment by DreamMaoMao** [comment]
In fact, I do remember the position and size of all the Windows, but when I switch back to the previous layout of the non-floating Windows in a workspace, they will be retiled by the original layout module, and I have a hard time controlling the behavior of these layout modules

**Comment by DreamMaoMao** [comment]
What layout did you use?

**Comment by DreamMaoMao** [comment]
I have supported this feature in dev branch:

you can try it:
git clone -b dev https://github.com/DreamMaoMao/hycov.git

Since there are many changes, I need your test to see if it is stable and then consider merging it into the main branch
