### ISSUE TITLE
Hardcoded Alt keycode 56 prevents using another key

### ISSUE THREAD

**Issue by csdvrx** [DreamMaoMao/hycov#33]
In function hkOnKeyboardKey() at line 206 of globaleventhook.cpp, the keycode 56 is hardcoded:

      if(g_enable_alt_release_exit && g_isOverView && e->keycode == 56 && e->state == WL_KEYBOARD_KEY_STATE_RELEASED) {

This prevents the shortcuts to be mapped with other keys like:

    $mainMod = SUPER
    bind = $mainMod,tab,hycov:toggleoverview

I suggest reading the equivalent of keycode 56 from the toggleoverview bind, so that it can be different from the Alt key

**Comment by DreamMaoMao** [comment]
This doesn't seem to be a very high priority, I will support him when I have time, of course welcome to pr if you have time

**Comment by DreamMaoMao** [comment]
当前插件接口并不支持从配置中查找某个命令绑定了什么按键,如果要这个就要自己做大量的工作去解析配置文件,而且每次触发都去解析哦一次太过于低效,我更倾向于在hycov中加一个选项去指定替代按键.like:
```
hycov {
  alt_release_key_replace = SUPER
}
```

**Comment by DreamMaoMao** [comment]
done 

![image](https://github.com/DreamMaoMao/hycov/assets/30348075/9f772dad-739c-4fd1-9a34-8f916b517b91)
