### ISSUE TITLE
Microsoft Edge shows a black preview screen then crashes

### ISSUE THREAD

**Issue by csdvrx** [DreamMaoMao/hycov#37]
Hycov works great with most windows except with Edge.

When I have a Edge browser open, hycov toggle shows:
 - very briefly the Edge window content
 - then it's replaced by black
 - a few seconds later, Edge window content appears again

If I use hycov a few times, Edge freezes and is not responsive until I do `killall msedge`

Edge has been very stable before I used hycov.

The cause is unknown. I can try to log more information if you tell me what would help

**Comment by DreamMaoMao** [comment]
I've been using edge and there's no problem
https://github.com/DreamMaoMao/hycov/assets/30348075/5fd96824-1921-4886-a63f-e124edf480c2

**Comment by csdvrx** [comment]
That's strange, I will try to do a OBS record of when the issue happens!

**Comment by daUnknownCoder** [comment]
i saw the problem, is your ms edge on the latest version? coz mine's not and it freezes in hycov

**Comment by DreamMaoMao** [comment]
Unfortunately, I was not able to reproduce it, which may have something to do with the fact that different machines use different graphics drivers
