### ISSUE TITLE
Feature request: Add to hyprland-plugins

### ISSUE THREAD

**Issue by julius-boettger** [DreamMaoMao/hycov#38]
Hyprland got [a new plugin system](https://github.com/hyprwm/hyprland-plugins) with its latest release, [0.34.0](https://github.com/hyprwm/Hyprland/releases/tag/v0.34.0). I would like to be able to install Hycov through the new plugin system, hyprland-plugins.

**Comment by DreamMaoMao** [comment]
same issue: #40
