### ISSUE TITLE
Config ignored if installed with hyprpm

### ISSUE THREAD

**Issue by IgnazNepumuk** [DreamMaoMao/hycov#40]
I wanted to try out the new Hyprland Plugin Manager (hyprpm), but it looks like the config parameters get ignored.

How do I configure hycov if installed via hyprpm?

**Comment by DreamMaoMao** [comment]
I haven't used hyprpm, I will do some research when I have free time

**Comment by DreamMaoMao** [comment]
You can try the latest version and it should be ready to use

**Comment by IgnazNepumuk** [comment]
Updated via hyprpm and it fixed the issue. 

Thank you.
