### ISSUE TITLE
windows appear above monitor

### ISSUE THREAD

**Issue by dmxk062** [DreamMaoMao/hycov#49]
first of all, awesome plugin. but i seem to get an issue on my desktop, since i have a vertical offset on some of my monitors.
 as a result, the windows appear outside of that workspace when i activate my monitor(above). if i set the vertical offset to 0, it works 
![2024_01 07_17:08:39_sc](https://github.com/DreamMaoMao/hycov/assets/138803455/d1faa842-ff58-4ccf-b4ed-5d933dcfc76d)
i assume that its just a matter of taking a workspace's vertical offset into account, but since i dont know cpp i dont know how i'd do that.

**Comment by DreamMaoMao** [comment]
https://github.com/DreamMaoMao/hycov/pull/50

maybe fixed, try

**Comment by dmxk062** [comment]
this fixes it, thanks a  lot
