### ISSUE TITLE
Need better documentation in Readme

### ISSUE THREAD

**Issue by VoKi21** [DreamMaoMao/hycov#51]
Couldn't get gestures working and make use of enable_alt_release_exit. i have this in my config:

```
plugin {
    hycov {
        overview_gappo = 60 # gaps width from screen edge
        overview_gappi = 24 # gaps width from clients
        hotarea_size = 10 # hotarea size in bottom left,10x10
        enable_hotarea = 1 # enable mouse cursor hotarea     
        swipe_fingers = 4 # finger number of gesture, move any directory
        move_focus_distance = 100 # distance for movefocus, only can use 3 finger to move 
        enable_gesture = 1 # enable gesture
        disable_workspace_change = 0 # disable workspace change when in overview mode
        disable_spawn = 0 # disable bind exec when in overview mode
        auto_exit = 1 # enable auto exit when no client in overview
        auto_fullscreen = 0 # auto make active window maximize after exit overview
        only_active_workspace = 0 # only overview the active workspace
        only_active_monitor = 0 # only overview the active monitor
        enable_alt_release_exit = 1 # alt swith mode, see readme for detail
        alt_toggle_auto_next = 1 # auto focus next window when toggle overview in alt swith mode
    }
}

bind = ALT, TAB, hycov:toggleoverview
bind = ALT, left, hycov:movefocus, l
bind = ALT, right, hycov:movefocus, r
bind = ALT, up, hycov:movefocus, u
bind = ALT, down, hycov:movefocus, d
```

but alt + tab doesnt work as it should according to config (maybe add more examples with all possible usecases). and gestures also dont work at all (maybe because i have workspace switch on swipe, but i dont think they should conflict anyway)
also that wouldnt be bad if any native english speaker recheck the orthography and punctuation

**Comment by DreamMaoMao** [comment]
1. What is the version of hyprland?
2. How did you install this plugin?
3. Do all features not work or just these two features not work?
4. After configuration you try to log out and try to log in again?

**Comment by VoKi21** [comment]
okay maybe i should try rebooting before writing issue
1. v0.34.0
2. hyprpm
3. these two features didn't work before rebooting, now everything is okay. other features worked.
4. i tried
also having enteroverview with the flag causes unwanted behaviour: alt-tab enters overview, but next alt-tab enters one more overview. releasing alt exits all overviews. but that's more about my second issue
after rebooting gestures and multiple alt-tab-tab-tab toggle work as described
