### ISSUE TITLE
Multiple hycov:enteroverview causes different glitches and bugs

### ISSUE THREAD

**Issue by VoKi21** [DreamMaoMao/hycov#52]
as wrote in the title, having this string:
`bind = ALT, TAB, hycov:enteroverview`
and pressing alt+tab multiple times causes overview open more and more times (you should try yourself). after choosing a window, all clients are on one workspace and have random sizes (information about workspace and size is lost). possible way to fix: not allow entering overview while in overview

**Comment by DreamMaoMao** [comment]
I can't understand your description, can you record a video ?

**Comment by DreamMaoMao** [comment]
`bind = ALT, TAB, hycov:toggleoverview`  I suggest you to use this , not enteroverview

**Comment by VoKi21** [comment]
https://github.com/DreamMaoMao/hycov/assets/74360792/67743536-ca8d-4773-a169-abb1743191d3

yes i use toggle, but i've noticed a bug and wanted to report
also when alt-tabbing ~10 times, whole Hyprland crashes (cant record)

**Comment by DreamMaoMao** [comment]
it have fixed in latest commit.
