### ISSUE TITLE
hycov cause cruse after an update

### ISSUE THREAD

**Issue by gfhdhytghd** [DreamMaoMao/hycov#55]
Everytime I try to start hycov, hyprland crush

~ » hyprctl version                                                                      wilf@Arch
Hyprland, built from branch main at commit babb9c07b045e21b5549cdcc3096d677e9db35b3  (swipe: Prevent hiding current workspace when swiping (4417)).
Date: Fri Jan 12 02:22:40 2024
Tag: v0.34.0-41-gbabb9c07

flags: (if any)

[hyprlandCrashReport2807.txt](https://github.com/DreamMaoMao/hycov/files/13910722/hyprlandCrashReport2807.txt)

**Comment by DreamMaoMao** [comment]
Do you mean after you update hyprland or after you update hycov?

which one did you update?

**Comment by gfhdhytghd** [comment]
yay -Syyu
hyvoc was installed yesterday 4pm UTC+8, according to the time record on github it shuldn't change since then, so it should be cause by the update of hyprland or other dependence.

**Comment by DreamMaoMao** [comment]
If you updated hyprland after hycov, you may need to recompile hycov,

**Comment by gfhdhytghd** [comment]
ok thanks

**Comment by gfhdhytghd** [comment]
may you delete all the "$" in the readme.md,it could make it easyer for copy

**Comment by DreamMaoMao** [comment]
Makes sense
