### ISSUE TITLE
Feature request: cross-monitors overview

### ISSUE THREAD

**Issue by SamueleFacenda** [DreamMaoMao/hycov#62]
One thing that I would love to have in my multi-monitor setup is the ability to switch easily to any window in any workspace or
monitor. Currently with hycov I can cycle only between windows of workspaces on the same monitor.
I think that there can be two ways of doing so:
- one: keep this layout but add an option to cycle/move also to other monitors. This wold be (I think) not so difficult for cycling 
but harder for moving (since is required to know the spatial position of the monitors), but default dispatchers already let you 
move the focus around.
- two: having an overview in one monitor with all the windows, and when one is selected the focus moves to the right monitor 
and workspace. This one would require some more work I think.

**Comment by DreamMaoMao** [comment]
done , try this
![image](https://github.com/DreamMaoMao/hycov/assets/30348075/006ad6c4-b3cb-4dc6-a3e9-a9bf3b02179d)

**Comment by SamueleFacenda** [comment]
Awesome, it works, thanks!
Just a note, this cannot be activated if alt_release_exit and toggle_auto_next are activated, I think that the
problem is [here](https://github.com/DreamMaoMao/hycov/blob/8350c45aefe4a8f1be1b34a11f0c736617ccc89b/src/dispatchers.cpp#L285).
With the alt_release_exit alone it works well.

**Comment by DreamMaoMao** [comment]
> Awesome, it works, thanks! Just a note, this cannot be activated if alt_release_exit and toggle_auto_next are activated, I think that the problem is [here](https://github.com/DreamMaoMao/hycov/blob/8350c45aefe4a8f1be1b34a11f0c736617ccc89b/src/dispatchers.cpp#L285). With the alt_release_exit alone it works well.

try latest commit, may fixed.

**Comment by SamueleFacenda** [comment]
Yes!
