### ISSUE TITLE
yo i got a problem, `Invalid dispatcher, requsted "hycov:movefocus" does not exist`

### ISSUE THREAD

**Issue by daUnknownCoder** [DreamMaoMao/hycov#64]
![image](https://github.com/DreamMaoMao/hycov/assets/84800625/b6915a5b-4a53-4a76-9b38-96f697de3a86)

i installed hycov with [hyprpm](https://wiki.hyprland.org/Plugins/Using-Plugins/#hyprpm)

its installed on the latest main version :
Hyprland, built from branch HEAD at commit 03ebbe18ed8517ee22591eac82cd54322f42cb7d  (props: bump ver to 0.34.0).
Date: Mon Jan 1 12:03:15 2024
Tag: v0.34.0

flags: (if any)

`extra/hyprland 0.34.0-1 [installed]`

so i dont know why its happening

how i m using it:
```hypr
plugin {
  hycov {
    overview_gappo = 50 # gaps width from screen edge
    overview_gappi = 14 # gaps width from clients
    hotarea_size = 10 # hotarea size in bottom left,10x10
    enable_hotarea = 1 # enable mouse cursor hotarea     
    swipe_fingers = 4 # finger number of gesture,move any directory
    move_focus_distance = 100 # distance for movefocus,only can use 3 finger to move 
    enable_gesture = 0 # enable gesture
    disable_workspace_change = 0 # disable workspace change when in overview mode
    disable_spawn = 0 # disable bind exec when in overview mode
    auto_exit = 1 # enable auto exit when no client in overview
    auto_fullscreen = 0 # auto make active window maximize after exit overview
    only_active_workspace = 0 # only overview the active workspace
    only_active_monitor = 0 # only overview the active monitor
    enable_alt_release_exit = 0 # alt swith mode,see readme for detail
    alt_toggle_auto_next = 0 # auto focus next window when toggle overview in alt swith mode
    click_in_cursor = 1 # target windwo is find by cursor, not the current foucus window.
    hight_of_titlebar = 0 # height deviation of title bar hight
    enable_alt_release_exit = 1
  }
}
# bind key to toggle overview(force mode,no affected by `only_active_workspace` and `only_active_monitor`)
bind = ALT,tab,hycov:toggleoverview,forceall
bind=ALT,left,hycov:movefocus,l
bind=ALT,right,hycov:movefocus,r
bind=ALT,up,hycov:movefocus,u
bind=ALT,down,hycov:movefocus,d
```

![image](https://github.com/DreamMaoMao/hycov/assets/84800625/735cf4a2-dfad-43bd-84c3-8f4529be0d90)

**Comment by DreamMaoMao** [comment]
You need to log out and log back in each time you install it.

**Comment by DreamMaoMao** [comment]
But this error message will appear briefly every time you log in, which is unavoidable,

If you want to avoid this message popping up, I recommend not using hyprpm reload to launch the plugin.

Instead, load the plugin directly on the configuration:

#hyprpm will install the.so file in the /usr/local/lib path
plugin = /usr/local/lib/libhycov.so

refer:
https://github.com/hyprwm/Hyprland/discussions/4373

**Comment by 0a00** [comment]
✖ headers are not up-to-date, please run hyprpm update.


![图片](https://github.com/DreamMaoMao/hycov/assets/59482058/da410a78-d3ed-4ef5-8245-331ca97933d2)
![图片](https://github.com/DreamMaoMao/hycov/assets/59482058/f95821ff-6dfb-4718-8eeb-c840ae65822f)

**Comment by 0a00** [comment]
Hello, it seems that an update is needed in the latest version

**Comment by DreamMaoMao** [comment]
This message seems to be telling  you to run

The 'hyprpm update' command 

instead of requiring the plugin repository to do something

**Comment by 0a00** [comment]
Oh, dear, but
![图片](https://github.com/DreamMaoMao/hycov/assets/59482058/75b6ba05-9bab-49b4-a7ce-d58577475b51)

**Comment by 0a00** [comment]
This was after I updated hyprland-git today

**Comment by DreamMaoMao** [comment]
how did you install  hyprland-git?

**Comment by 0a00** [comment]
![图片](https://github.com/DreamMaoMao/hycov/assets/59482058/a9ffb165-bc47-4f74-8530-881d974fc73f)

**Comment by DreamMaoMao** [comment]
It seems that the hyprpm tool has a bug update, even if you do not use hycov, you can not use other official plugins, you may should submit a bug report to the hyprland community.  

@0a00

**Comment by 0a00** [comment]
OK,thanks

**Comment by daUnknownCoder** [comment]
> ![图片](https://private-user-images.githubusercontent.com/59482058/300357728-a9ffb165-bc47-4f74-8530-881d974fc73f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1MTI4OTcsIm5iZiI6MTcwNjUxMjU5NywicGF0aCI6Ii81OTQ4MjA1OC8zMDAzNTc3MjgtYTlmZmIxNjUtYmM0Ny00Zjc0LTg1MzAtODgxZDk3NGZjNzNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDA3MTYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjN2EwM2JkNmRiZDlhNmU0Y2NkZjRmMjEzYTM2NDkyMGRmMjRkN2M1MDE1ZjMyMWI2ZmU0NzgzOTVkZWI3YmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SrlCl3aJzseAiPvW7JnvDIi5wqbkpGwDHhvhJqfdgfE)

That happened to me as well so I downgraded to hyprland from pacman as the installed version from git clone is 0.34 but the latest maintained on aur is 0.31 so just install the pacman hyprland

**Comment by daUnknownCoder** [comment]
> #hyprpm will install the.so file in the /usr/local/lib path plugin = /usr/local/lib/libhycov.so

But if I use it as `plugin = /usr/local/lib/libhycov.so` I am stuck in an sddm loop

**Comment by DreamMaoMao** [comment]
> > #hyprpm will install the.so file in the /usr/local/lib path plugin = /usr/local/lib/libhycov.so
> 
> But if I use it as `plugin = /usr/local/lib/libhycov.so` I am stuck in an sddm loop

how about this?
1. rmove your config `plugin = /usr/local/lib/libhycov.so`


2. rebuild hycov  manually
```
git clone https://github.com/DreamMaoMao/hycov.git
cd hycov
bash install.sh # `libhycov.so` path: /usr/lib/libhycov.so
```
3.
then change you plugin config from  `plugin = /usr/local/lib/libhycov.so` to `plugin = /usr/lib/libhycov.so`.

**Comment by daUnknownCoder** [comment]
yeah did that, `plugin = ...` still doesn't work
this works `exec-once = hyprctl plugin load /usr/lib/libhycov.so` so hyprctl does it... thanks anyway

**Comment by daUnknownCoder** [comment]
yeah did that, `plugin = ...` still doesn't work
this works `exec-once = hyprctl plugin load /usr/lib/libhycov.so` so hyprctl does it... thanks anyway

**Comment by DreamMaoMao** [comment]
refer to this:

https://github.com/hyprwm/Hyprland/issues/4284

**Comment by DreamMaoMao** [comment]
> refer to this:
> 
> [hyprwm/Hyprland#4284](https://github.com/hyprwm/Hyprland/issues/4284)

Every time you use yay-S hyprland-git to update hyprland, you need rm -rf /usr/include/hyprland and then run the hyprpm update update

@0a00 @daUnknownCoder

**Comment by 0a00** [comment]
Thank you very much. Problem solved
