### ISSUE TITLE
BUG: Jumpin by click in overview mode not working when `enable_hotarea=0`

### ISSUE THREAD

**Issue by fedoranvar** [DreamMaoMao/hycov#66]
Good day to you!

**Expected behaviour:**
Jumping by click to windows in overview mode  when  `enable_hotarea=0` 

**Actual Behavior:**
Jumping by click only works if `enable_hotarea=1` 

**Version**: 171800deb10b568aa8a01b58a1677c3d0dd6ffa7

Thank you!

**Comment by DreamMaoMao** [comment]
This is not a bug, it is deliberately disabled together, maybe I think too much, now it has been separated, you can try the latest commit
