### ISSUE TITLE
Change workspaces settings for overview workspace?

### ISSUE THREAD

**Issue by jasper-at-windswept** [DreamMaoMao/hycov#68]
I'm trying to make it so windows have borders in the overview workspace so I can see what window is active.

I have tried using the below configuration but neither has worked, any ideas how to do it correctly?

```
workspace = name:OVERVIEW, border:true, bordersize:2
workspace = special:OVERVIEW, border:true, bordersize:2
```

**Comment by DreamMaoMao** [comment]
https://github.com/DreamMaoMao/hycov/commit/a8847d230f328d4da3418bb087f22aeaa4bb3146

try latest commit

**Comment by DreamMaoMao** [comment]
workspace=name:OVERVIEW,bordersize:5

**Comment by jasper-at-windswept** [comment]
I'll give it a try in an hour and get back to you thanks!

**Comment by jasper-at-windswept** [comment]
> [a8847d2](https://github.com/DreamMaoMao/hycov/commit/a8847d230f328d4da3418bb087f22aeaa4bb3146)
> 
> try latest commit

I just tried it now with the line below and it is not working.

`workspace = name:OVERVIEW, border:true, bordersize:2`

**Comment by jasper-at-windswept** [comment]
After double checking the new version was loaded I can confirm it is not working.

I tried with the below line.

`workspace = name:OVERVIEW, border:true, bordersize:2`

**Comment by DreamMaoMao** [comment]
Are you sure you've updated hycov to the latest?

**Comment by DreamMaoMao** [comment]
https://github.com/DreamMaoMao/hycov/assets/30348075/98446e2d-9d24-40d2-ba16-9ae3d20e7e47

it work for me

**Comment by jasper-at-windswept** [comment]
@DreamMaoMao 
My flake.lock confirms the commit number and i did see the file path change in hyprland.conf.

```nix
"hycov": {
      "inputs": {
        "hyprland": [
          "hyprland"
        ]
      },
      "locked": {
        "lastModified": 1707294610,
        "narHash": "sha256-+rSTKZnVHGYBkxlL1aCA/8kR6ER7lv/uwDWfJvbSS6w=",
        "owner": "DreamMaoMao",
        "repo": "hycov",
        "rev": "a8847d230f328d4da3418bb087f22aeaa4bb3146",
        "type": "github"
      },
      "original": {
        "owner": "DreamMaoMao",
        "repo": "hycov",
        "type": "github"
      }
    },
```

**Comment by jasper-at-windswept** [comment]
Oh and that nix store hyprland.conf file contains this:
```conf
exec-once = /nix/store/vl5zykxl49zan3dkq8yhqfinyxg30lhh-dbus-1.14.10/bin/dbus-update-activation-environment --systemd DISPLAY HYPRLAND_INSTANCE_SIGNATURE WAYLAND_DISPLAY XDG_CURRENT_DESKTOP && systemctl --user stop hyprland-session.target && systemctl --user start hyprland-session.target
plugin=/nix/store/acivwxmgapa80d49c1wk1fpmqbmv7lb2-hycov-0.1/lib/libhycov.so
source=~/.config/hypr/hypr.conf
```

**Comment by jasper-at-windswept** [comment]
@DreamMaoMao 
I think there is a bigger issue though because when I try to use one of the other options you setup `rounding` it also does not apply.

`workspace = name:OVERVIEW, rounding:false` but windows are still rounded

**Comment by DreamMaoMao** [comment]
because i only add the bodersize rule

**Comment by jasper-at-windswept** [comment]
> because i only add the bodersize rule

Hm, well i just tried again with only the bordersize rule but sadly still not working for me.

`workspace = name:OVERVIEW, bordersize:20`

**Comment by DreamMaoMao** [comment]
Sorry, I have tried several Hyprland versions without any problem, maybe the problem appears in your environment, but I am not very familiar with nix

**Comment by jasper-at-windswept** [comment]
@DreamMaoMao 
I'm using the latest version of Hyprland and I made sure that I was building the latest version by cloning this repository and pulling from there.

I also tried removing all my configurations except for the ones directly related to this plugin but it still is not showing borders.

**Comment by jasper-at-windswept** [comment]
Good News, I got it to work but only by hard setting the value of borderSize to 2.

https://github.com/jasper-at-windswept/hycov/commit/3809ae2ccee11617e302d822a1faf23e59bf92b2

**Comment by DreamMaoMao** [comment]
This means that your workspace rules are not set correctly in nix, so hyprland is not reading your workspace rules

**Comment by jasper-at-windswept** [comment]
> This means that your workspace rules are not set correctly in nix, so hyprland is not reading your workspace rules

Here is what i have in my nix home-manager configuration.
```nix
  wayland.windowManager.hyprland = {
    enable = true;
    package = hyprland.packages.${pkgs.system}.hyprland;
    xwayland.enable = true;
    plugins = [
      hycov.packages.${pkgs.system}.hycov
    ];
    settings = {
      source = "~/.config/hypr/hypr.conf";

      workspace = "name:OVERVIEW, bordersize:2";
    };
  };
```

**Comment by DreamMaoMao** [comment]
![Screenshot_2024-02-08-06-19-02-061_com.github.android.jpg](https://github.com/DreamMaoMao/hycov/assets/30348075/6b40cd90-8c6a-4619-972a-7907043fd68e)

maybe like this guy.

**Comment by jasper-at-windswept** [comment]
Yeah that is what I was doing previously.

https://gitlab.com/jasper-at-windswept/dots/-/blob/main/hypr/monitors.conf?ref_type=heads

**Comment by jasper-at-windswept** [comment]
I sourced monitors.conf from hypr.conf which was sourced from the nix generated hyprland.cong

**Comment by DreamMaoMao** [comment]
Instead of applying the overview workspace, you might try applying the rule to another workspace to see if it works

**Comment by jasper-at-windswept** [comment]
> Instead of applying the overview workspace, you might try applying the rule to another workspace to see if it works

I have tried that and yes it does work.
I can get borders on other specific workspaces.

**Comment by DreamMaoMao** [comment]
no special workspace .  try normal workspace

**Comment by DreamMaoMao** [comment]
workspace=3,bordersize:5  like this

**Comment by jasper-at-windswept** [comment]
> workspace=3,bordersize:5 like this

Yes I have tried that, it works perfectly fine for all other workspaces except the OVERVIEW one.

**Comment by DreamMaoMao** [comment]
How about this: if your current workspace is 3,

1. set `workspace=3, bordersize: 5`, and then go to overview. See if your border has any reservations under the overview.
3. set `workspace= name:3, bordersize: 5`, and then go to overview. See if your border has any reservations under the overview.


overview doesn't actually change the current workspace, just change the name,

I suspect nix may have converted the OVERVIEW name from uppercase to lowercase, resulting in hyprland not being able to find the workspace corresponding to the lowercase name

**Comment by jasper-at-windswept** [comment]
>     1. set `workspace=3, bordersize: 5`, and then go to overview. See if your border has any reservations under the overview.
> 
>     2. set `workspace= name:3, bordersize: 5`, and then go to overview. See if your border has any reservations under the overview.

Ok I just tried both of those for my main workspace and the borders do stay around the windows in Overview mode on that workspace.

I tried doing the below aswell but it did not work.
`workspace = name:overview, bordersize:2`

**Comment by DreamMaoMao** [comment]
what? both of two setting can work? 

`workspace= name:3, bordersize: 5` ,This shouldn't go into effect.
if this work,That means the name didn't change before the enter overview...

are you sure you are using the latest hycov ?

it this commit i do this:

https://github.com/DreamMaoMao/hycov/commit/a8847d230f328d4da3418bb087f22aeaa4bb3146 


![image](https://github.com/DreamMaoMao/hycov/assets/30348075/f42d90f7-f689-4c96-bff0-609d1b04cc26)

**Comment by jasper-at-windswept** [comment]
Maybe when I set `name:3` it just didn't update properly.

According to my flake.lock i am using the latest commit. https://github.com/DreamMaoMao/hycov/commit/69ecf80d493b4aa055aa427768a8dff9d38c65e4

**Comment by DreamMaoMao** [comment]
https://github.com/DreamMaoMao/hycov/assets/30348075/e70ce8b9-9225-4d89-955b-d2d967896458

As you can see in the video, the name changes after entering the ov mode so the name:3 rule is invalid

**Comment by jasper-at-windswept** [comment]
The simplest solution i can see here is just enabling `border_size = 2` by default and then disabling borders on all work spaces one by one like below.

I have double checked `hyprctl layers` and the overview layer is fully capitalized there and in Waybar but for some reason I can't access it using workspace rules. 

```
workspace = 1, monitor:DP-2, default:true, border:false
workspace = 2, monitor:DP-2, border:false
workspace = 3, monitor:DP-2, border:false
workspace = 4, monitor:DP-1, border:false
workspace = 5, monitor:DP-1, border:false
workspace = 6, monitor:DP-1, border:false
```

**Comment by DreamMaoMao** [comment]
This has nothing to do with case, because according to the results of previous tests, the name of the workspace did not change before entering ov mode.

**Comment by DreamMaoMao** [comment]
![image](https://github.com/DreamMaoMao/hycov/assets/30348075/9bf86bee-94d5-4720-b5dc-7c9e18df5b2c)


Can you show me your log, see if he changed his name before entering

**Comment by jasper-at-windswept** [comment]
> ![image](https://private-user-images.githubusercontent.com/30348075/303203893-9bf86bee-94d5-4720-b5dc-7c9e18df5b2c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczNjMwMTQsIm5iZiI6MTcwNzM2MjcxNCwicGF0aCI6Ii8zMDM0ODA3NS8zMDMyMDM4OTMtOWJmODZiZWUtOTRkNS00NzIwLWI1ZGMtN2M5ZTE4ZGY1YjJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA4VDAzMjUxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1OTgyODIzNGFkYmY3YjZkZjFlYzg4NzMzZGNkNDU3NGJjZGJjOTEwNGQzZWY4NjM3M2ZlZjVhOTAzNzg0MjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dMQUnJI72TlG2PDg9D92Ch0VU0NFEUIoXQ4saCcPQO0)
> 
> Can you show me your log, see if he changed his name before entering

Where can I find that log.sh?

**Comment by DreamMaoMao** [comment]
```bash
#!/usr/bin/bash

a=$(cd /tmp/hypr/ && ls -rt | tail -1)
tail -f /tmp/hypr/$a/hyprland.log
```

bash tool/log.sh | grep -E "workspace|enter"

**Comment by DreamMaoMao** [comment]
![image](https://github.com/DreamMaoMao/hycov/assets/30348075/b4ec2616-59e3-4016-9646-be7f10058c72)

**Comment by jasper-at-windswept** [comment]
> ```shell
> #!/usr/bin/bash
> 
> a=$(cd /tmp/hypr/ && ls -rt | tail -1)
> tail -f /tmp/hypr/$a/hyprland.log
> ```
> 
> bash tool/log.sh | grep -E "workspace|enter"

That returns the error below
And yes i made sure to add that disable_logs = false and rebooted my system

```
tail: cannot open '/tmp/hypr/a6ccd36147109d5cb2981122595f06ae93999b55_1707365755.lock/hyprland.log' for reading: Not a directory
tail: no files remaining
```

**Comment by DreamMaoMao** [comment]
Then you can go to this directory and find the latest date dir manually

/tmp/hypr/

**Comment by jasper-at-windswept** [comment]
@DreamMaoMao 
After checking the logs it looks the same as what you sent.

```
[LOG] [hycov] enter overview
[LOG] renameWorkspace: Renaming workspace 1 to 'OVERVIEW'
[LOG] [hycov] enter overview:alt switch mode auto next
[LOG] renameWorkspace: Renaming workspace 1 to '1'
```

**Comment by DreamMaoMao** [comment]
https://github.com/DreamMaoMao/hycov/commit/cdec254bdf775a7b2c6d10ba7169941d60551b64

please try this and show me again

**Comment by jasper-at-windswept** [comment]
> please try this and show me again

```
./log.sh | grep -E "workspace|enter|change to"

[LOG] [hycov] enter overview
[LOG] renameWorkspace: Renaming workspace 1 to 'OVERVIEW'
[LOG] [hycov] change to layout:ovgrid
[LOG] [hycov] enter overview:alt switch mode auto next
[LOG] renameWorkspace: Renaming workspace 1 to '1'
```

**Comment by DreamMaoMao** [comment]
everything look goo,   sorry  i have no idea what happen to you .
