### ISSUE TITLE
Overview doesn't autoexit

### ISSUE THREAD

**Issue by daxisunder** [DreamMaoMao/hycov#69]
It doesn't autoexit even after reboot, everything else works fine. (on Arch, installed with meson/ninja)

**Comment by DreamMaoMao** [comment]
Under what circumstances will it not automatically exit? I don’t quite understand what you mean.

can you record a video to show me what happen?

**Comment by jasper-at-windswept** [comment]
> It doesn't autoexit even after reboot, everything else works fine. (on Arch, installed with meson/ninja)
@daxisunder 

I found reinstalling/building it fixes this issue.

**Comment by daxisunder** [comment]
> Under what circumstances will it not automatically exit? I don’t quite understand what you mean.

enable_alt_release_exit=1 doesn't work, I have to press Tab again to exit overview.

**Comment by DreamMaoMao** [comment]
![image](https://github.com/DreamMaoMao/hycov/assets/30348075/d0d83ed4-865c-41f2-83f4-719e248709b4)

Try use  this to  specifying your key code
