### ISSUE TITLE
Instructions for hyprpm

### ISSUE THREAD

**Issue by 10b14224cc** [DreamMaoMao/hycov#71]
Can this be installed with hyprpm?

If so, can we have instructions in the README?

**Comment by DreamMaoMao** [comment]
![image](https://github.com/DreamMaoMao/hycov/assets/30348075/af051818-1392-4a5b-82b0-917050acbe04)

**Comment by 10b14224cc** [comment]
You literally just committed them:

![image](https://github.com/DreamMaoMao/hycov/assets/151393205/b3baf913-fc9d-4e46-91e1-15c71230e50c)

**Comment by 10b14224cc** [comment]
Anyway, thanks!
