### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by craftergarage** [DreamMaoMao/hycov#73]
$ bash install.sh

I'm trying to build and I'm getting the following errors.

![image](https://github.com/DreamMaoMao/hycov/assets/121237802/6bd3ef34-2b7c-4e3d-99aa-eca948e05937)

hyprctl version
Hyprland, built from branch main at commit a6ccd36147109d5cb2981122595f06ae93999b55 dirty (screencopy: move monitor verif check to the proper place).
Date: Thu Feb 8 02:47:14 2024
Tag: v0.35.0-8-ga6ccd361

**Comment by DreamMaoMao** [comment]
How did you install hyprland? Try using hyprpm to install it.

**Comment by DreamMaoMao** [comment]
It looks like your wlroots environment is a bit messy, I suggest you reinstall side hyprland-git
To update the wlroots header file of the system

**Comment by craftergarage** [comment]
yay -S hyprland-git

I got this error when I installed the latest version of hyprland.

sudo pacman -S hyprland

I did not encounter any errors when I installed it this way. When compiling in the new version, it cannot find wlroot.

**Comment by DreamMaoMao** [comment]
maybe something wrong with tha aur package  (maybe the pkgbuild script not update the wlroots)

when I manually git clone the latest hyprland , there are no problem.

**Comment by DreamMaoMao** [comment]
sudo pacman -S hyprland   this is to install V0.34 rely on old wlroots, your wlroots header is old.  and yay -S hyprland-git not update the wlroots for you .

**Comment by craftergarage** [comment]
When I installed hyprland-git, I noticed that wlroots was not installed. After some research, I found that when I installed wlroots-git via yay, the problem was solved.

yay -S hyprland-git wlroots-git

You can close the issue :) thank you.

**Comment by DreamMaoMao** [comment]
It stands to reason that the hyprland-git script will automatically install wlroots

There may be a problem somewhere, causing hyprland-git not to automatically update wlroots
