### ISSUE TITLE
[Feature] Allow Gesture Swipe Direction Customization

### ISSUE THREAD

**Issue by maydayv7** [DreamMaoMao/hycov#74]
Currently the overview is activated by swiping fingers in any direction. Could it be possible to configure the direction of swipe for activating the overview?

For example, I would like to be able to swipe up with 3 fingers to enter the overview, but currently setting `swipe_fingers=3` activates overview on all swipes, thus disabling the workspace swipe

**Comment by DreamMaoMao** [comment]
If you want more complex gestures, I recommend disabling hycov's own gestures and using them in conjunction with a dedicated gesture plugin:

https://github.com/horriblename/hyprgrass

**Comment by maydayv7** [comment]
The problem is `hyprgrass` is meant for touchscreen devices only, while I use a touchpad

Anyways, no biggie, I've emulated my intended behaviour with [`libinput-gestures`](https://github.com/bulletmark/libinput-gestures) so it isn't a problem anymore

BTW, thanks a lot for making this amazing plugin!
