### ISSUE TITLE
Cannot switch windows when maximized or fullscreen

### ISSUE THREAD

**Issue by raffaem** [DreamMaoMao/hycov#75]
`hycov:movefocus` doesn't change windows when the focal window is maximized or fullscreened.

**Comment by DreamMaoMao** [comment]
The ov mode window does not support full screen, it will exit the ov mode directly

**Comment by raffaem** [comment]
I don't understand.

When I have a windows in fullscreen, I expect `hycov:movefocus l` to switch to the other window, the one behind it.

This is what happens in normal hyprland.

Instead it does nothing.
