### ISSUE TITLE
Overview randomly opens, even when keybindings not pressed.

### ISSUE THREAD

**Issue by jasper-at-windswept** [DreamMaoMao/hycov#77]
For some reason overview mode just randomly opens whilst I'm playing different games, I monitored it for a while and confirmed I'm not accidentally doing any key combinations it is completely random.

**Comment by jasper-at-windswept** [comment]
Oh ok well. Overview just opened randomly and then crashed the game in doing so.

**Comment by DreamMaoMao** [comment]
I don't think it's going to trigger automatically, if it's not the keyboard, it's your mouse sliding over the hot zone or the touchpad triggering the gesture

**Comment by jasper-at-windswept** [comment]
> I don't think it's going to trigger automatically, if it's not the keyboard, it's your mouse sliding over the hot zone or the touchpad triggering the gesture

Oh it could be my mouse. Could you please explain better in the readme what the hot zone actually is because I have no idea

**Comment by DreamMaoMao** [comment]
```conf
        enable_hotarea = 1 # enable mouse cursor hotarea, when cursor enter hotarea, it will toggle overview    
        hotarea_monitor = all # monitor name which hotarea is in, default is all
        hotarea_pos = 1 # position of hotarea (1: bottom left, 2: bottom right, 3: top left, 4: top right)
        hotarea_size = 10 # hotarea size, 10x10
```

**Comment by jasper-at-windswept** [comment]
Ah OK I think I understand now.
I'll disable the hotarea since I have no use for it.
