### ISSUE TITLE
For a split second when logging in hyprland shows an error for invalid dispatcher

### ISSUE THREAD

**Issue by niksingh710** [DreamMaoMao/hycov#81]
![image](https://github.com/DreamMaoMao/hycov/assets/60490474/a3639847-4b72-4610-9a70-58f14fb5d077)

is there any way to fix this?

**Comment by DreamMaoMao** [comment]
The only way to do this is not to use `hyprpm` but to compile it manually and load it with `plugin = /usr/lib/libhycov.so`

**Comment by niksingh710** [comment]
> The only way to do this is not to use `hyprpm` but to compile it manually and load it with `plugin = /usr/lib/libhycov.so`

Thanks for this ig then Hyprland can only resolve this.
