### ISSUE TITLE
Segfault after opening overview on one monitor with fullscreen window on second

### ISSUE THREAD

**Issue by dmxk062** [DreamMaoMao/hycov#85]
When modifying(floating, moving, closing etc) a previously fullscreen window on a secondary monitor after hycov was used on the other monitor, hyprland segfaults.

hycov configuration: 
```
plugin {
hycov {
    only_active_monitor = 1 
    enable_hotarea = 0
    auto_exit = 1
    enable_gesture = 1
    swipe_fingers = 4

    overview_gappo = 64
    overview_gappi = 24

    click_in_cursor = 0
}
}
```

[crash report](https://github.com/DreamMaoMao/hycov/files/14318548/hyprlandCrashReport846.txt)

**Comment by DreamMaoMao** [comment]
What are the segfaults you're talking about? hyprland crash?  

I don't understand what you mean, nor can I repeat your steps, you need to provide more detailed steps and results.

**Comment by DreamMaoMao** [comment]
https://github.com/DreamMaoMao/hycov/commit/e3b6c8aa91ef1fe0511bc81b8d0c40ad98efe01e

In theory, this plugin does not allow switching to other workspaces before exiting ov mode, I have disabled it

**Comment by dmxk062** [comment]
sorry, i was not precise enough. 
steps to reproduce:
- open two windows on a monitor
- make one of them fullscreen
- switch to another monitor with some windows open
- open overview
- fullscreen window exits fullscreen state, even though hycov is configured for the active monitor only
- exit overview
- window stays not fullscreened, bugged(border radius only applied on one side)
- interact with that window in any way(close it, fullscreen it again, move it)
- hyprland will crash

**Comment by DreamMaoMao** [comment]
hycov should exist as a switcher not as a resident layout, I think it was not designed to be used that way in the first place, so this action has been banned in the latest commit to avoid accidentally triggering an error :)
