### ISSUE TITLE
something is not right

### ISSUE THREAD

**Issue by Airmancooma** [DreamMaoMao/hycov#86]
I had to rebuild my arch linux and what worked fine until now (bind=SUPER,TAB,hycov:toggleoverview) so far when I pressed the button the apps appeared like on gnome. But now on the new redndser it just sets the z index for some reason to make an app appear in front or behind another window. I can't make sense of this because I was doing specifically the same thing as on my old system. Any idea?

**Comment by DreamMaoMao** [comment]
no idea what happen to you

**Comment by Airmancooma** [comment]
So now I'm pressing my overview button key combination and it's not doing what it's supposed to do 

https://github.com/DreamMaoMao/hycov/assets/107194958/9ec88a74-604a-47b0-81f5-e95e8293c133

**Comment by DreamMaoMao** [comment]
check ,  it you install hycov and config it  by a right method, you will see what hycov is doing.  it you can't see `[hycov]` word in log. maybe you keybind has some problem. it don't trigger hycov.
