### ISSUE TITLE
Use a thumbnail of each app rather than resizing each app in the overview

### ISSUE THREAD

**Issue by SnipeXandrej** [DreamMaoMao/hycov#87]
Hi!

In the current state, the plugin firstly resizes all open apps, which are then placed in a grid.

I wonder if it would be possible to implement an option to not resize the apps when going in/out of overview, but instead use a "thumbnail" of each app that then gets scaled appropriately in the overview.

This approach has at least 2 upsides...
1. the apps don't get resized every time we enter or exit the overview
2. when apps get resized, they get really really small, and this makes it harder to recognize which app is which. This could be solved by using the aforementioned thumbnails.

One way to obtain a thumbnail of each app is by using pipewire, though there may be other methods that I am not aware of.

I guess this won't be easy to implement, but I think it will improve the experience.

Thanks.

**Comment by DreamMaoMao** [comment]
This sounds more like something to develop another standalone application, but if you are using window scaling instead of using window size resize this issue has been discussed before, hyprland has no interface support for the time being

https://github.com/hyprwm/Hyprland/issues/3861
