### ISSUE TITLE
Build error, missing transform.h

### ISSUE THREAD

**Issue by lividhen** [DreamMaoMao/hycov#88]
Have latest wlroots from aur installed.
Trying to build commit f6eb3618e9af6339ac8d52f295f6e5b932df0294 (latest as of writing).
I am given this error:
```
In file included from /usr/include/hyprland/src/debug/Log.hpp:7,
                 from ../src/log.hpp:3,
                 from ../src/globals.hpp:3,
                 from ../src/dispatchers.hpp:2,
                 from ../src/globaleventhook.cpp:3:
/usr/include/hyprland/src/includes.hpp:108:10: fatal error: wlr/util/transform.h: No such file or directory
  108 | #include <wlr/util/transform.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
==> ERROR: A failure occurred in build().
    Aborting...```

**Comment by DreamMaoMao** [comment]
It seems that you have lost the wlr header for some reason.

Try reinstalling hyprland-git or just wlroot-git

**Comment by lividhen** [comment]
Still having the same issue. Tried with both packages.

**Comment by DreamMaoMao** [comment]
1.uninstall hyprland-git wlroots-git

2. rm these dir
/usr/include/hyprland/
/usr/include/wlr/
/usr/local/include/hyprland/
/usr/local/include/wlr/

3. reinstall hyprland-git


try this

**Comment by lividhen** [comment]
Ayyyy that worked. Thank you so much for the help!
