### ISSUE TITLE
Trackpad 1:1 gestures

### ISSUE THREAD

**Issue by TheSunCat** [DreamMaoMao/hycov#9]
This plugin looks and feels great! I'd love to be able to use it with my trackpad directly (like swiping on Hyprland to switch workspace). There could be a configuration option for a swipe direction and number of fingers, then animate the effect alongside the movement on the trackpad.

**Comment by DreamMaoMao** [comment]
The ability to switch between work areas by gesture seems to have existed for hyprland

**Comment by DreamMaoMao** [comment]
![image](https://github.com/DreamMaoMao/hycov/assets/30348075/5e866362-ff0b-4b9c-8ad6-45296fd92d19)

**Comment by DreamMaoMao** [comment]
https://wiki.hyprland.org/Plugins/Development/Event-list/

This function cannot be implemented temporarily
Because hyprland hasn't added a hook for gesture events yet.

**Comment by DreamMaoMao** [comment]
https://github.com/hyprwm/Hyprland/issues/3696

I made an addition suggestion to hyprland

**Comment by TheSunCat** [comment]
Thanks! The gesture for toggling it works, but it is not 1:1 (unless I am misunderstanding the config). In a 1:1 gesture, the animation should follow along as you swipe, like swiping for workspaces works. There is an animation here: https://forty.gnome.org/
