### ISSUE TITLE
Window Groups Handling

### ISSUE THREAD

**Issue by maydayv7** [DreamMaoMao/hycov#92]
When a group along with other windows are present, the overview glitches when the windows in the group are cycled. Also the order of windows displayed isn't consistent, the position of the currently active group window isn't respected

https://github.com/DreamMaoMao/hycov/assets/73811274/5b0b7220-24c7-4690-ba3d-96a2fe18f272

**Comment by maydayv7** [comment]
All I did was change the active window in the group using the `changegroupactive` dispatcher as a keybinding: `bind="$mod, Tab, changegroupactive, f"`

**Comment by DreamMaoMao** [comment]
https://github.com/DreamMaoMao/hycov/commit/194f8776d8947a7d89d68c9613d6a0157923cc18

This commit support the group active window to be restored properly.

But you can't close a window in the group in ov mode and you can't change the active window in the group. I have not yet written any group operation logic code in the ov mode layout

**Comment by DreamMaoMao** [comment]
https://github.com/DreamMaoMao/hycov/commit/d2aacdfaf685412e7f3867d2ab305f869e951150

have support use group in overview mode
