### ISSUE TITLE
movefocus feature implementation

### ISSUE THREAD

**Issue by lucyColeclough** [DreamMaoMao/hycov#94]
Hi there, I want to implement some of the cross monitor support to `hycov:movefocus` as found in the [original function](https://github.com/hyprwm/Hyprland/blob/d92da7959a1d271c585d0a7de4c75a389bd1ac05/src/managers/KeybindManager.cpp#L1130)

I could add it [here](https://github.com/DreamMaoMao/hycov/blob/main/src/dispatchers.cpp#L222)
And it could perhaps be an additional argument or dispatcher if not always desired

I am going to sleep now, but if you are awake, may I have your opinion on this addition

Many thanks for the project

**Comment by DreamMaoMao** [comment]
This does not seem to have much to do with the functionality of this plugin, but rather an additional focus switch scheduling, and does not conflict with the current plugin, I think you can write a separate plugin to implement it

**Comment by lucyColeclough** [comment]
@DreamMaoMao
The reason i mention is that binding `hycov:movefocus` to hjkl for example, does not only switch windows in the overview, but also everywhere else,
so one must replace `movefocus` with `hycov:movefocus` to avoid double movement.
That is ok, but then the feature where one can move between monitors using `movefocus` is lost as it is not implemented in `hycov:movefocus` which is what i proposed to implement.

It can be done with submaps but it is fiddly, i am using submaps for now

**Comment by lucyColeclough** [comment]
I wanted to get your thoughts, but this is not the territory of another plugin

**Comment by DreamMaoMao** [comment]
I don't quite understand, bind hycov:movefocus move window focus

And binding movefoucs mobile display focus why does it conflict?

Don't they bind to different  key?

**Comment by DreamMaoMao** [comment]
oh oh, I think I know what you mean

**Comment by lucyColeclough** [comment]
yeah so adding move montior support to hycov:movefocus if not in the overview would allow it to behave like movefocus
i was going to try and do this in a submap though, maybe easier, like
```
bind= SUPER, h, movefocus
...
bind= SUPER, space, hycov:enteroverview
bind= SUPER, space, submap, overview
submap= overview
bind= SUPER, h, hycov:movefocus
...
bind= SUPER, space, hycov:;leaveoverview
bind= SUPER, space, submap, reset
submap= reset
```

**Comment by DreamMaoMao** [comment]
have dont in:

https://github.com/DreamMaoMao/hycov/commit/2f17ef51566f7be4912ce4104445651d3a83dbc5

**Comment by lucyColeclough** [comment]
Oh shit, i did mean id do it, but thanks!
