### ISSUE TITLE
Option to show windows from special workspaces in overview

### ISSUE THREAD

**Issue by luravoid** [DreamMaoMao/hycov#95]
I couldn't find if it's currently possible to show windows from special workspaces but it would be nice to have option in the plugin config like this:
```
special_workspaces = 1 # Show windows from special workspaces in overview
special_workspaces = 0 # Don't show
```

**Comment by DreamMaoMao** [comment]
Is this really necessary? You can also bring up Windows in special  workspace by doing the same as in normal mode

**Comment by DreamMaoMao** [comment]
https://github.com/DreamMaoMao/hycov/commit/ad2f97861428a0048dd2ea85df3fb7e2c98cc3a3

done
