### ISSUE TITLE
If workspace has on-created-empy rule then focusing window with hycov spawn new window on that workspace

### ISSUE THREAD

**Issue by luravoid** [DreamMaoMao/hycov#96]
Bug occurs for normal as for special workspaces:

I tested it with these rules:
```
workspace = 7, on-created-empty:kitty
workspace=special:type,gapsin:15,gapsout:64, on-created-empty:brave --app=https://monkeytype.com
```

https://github.com/DreamMaoMao/hycov/assets/103893901/f67c30f4-79af-4f42-a2d1-d18eb2c474fc

**Comment by DreamMaoMao** [comment]
fixed:

https://github.com/DreamMaoMao/hycov/commit/05fb15703d07a372b14a3260a337de13d1c16b91
